# Generated by Django 5.0.1 on 2024-04-07 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderitems_order_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='store.order'),
        ),
    ]
